version: '3'

services:

  rockiot:
    build:
      context: rockiot
      dockerfile: ./Dockerfile.prod
    env_file:
      - db.prod.env
      - rockiot.prod.env

  rockiotworker:
    env_file:
      - db.prod.env
      - rockiot.prod.env

  rockiotbeat:
    env_file:
      - db.prod.env
      - rockiot.prod.env

  rockiotlistener:
    env_file:
      - db.prod.env
      - rockiot.prod.env

  rockiot_ingest:
    env_file:
      - db.prod.env
      - rockiot.prod.env

  nodeexporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    expose:
      - "9100:9100"
    networks:
      - app-tier

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.40.0
    container_name: cadvisor
    privileged: true
    devices:
      - /dev/kmsg:/dev/kmsg
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
      - /cgroup:/sys/fs/cgroup:ro
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - app-tier
