version: '3'

services:

  timescaledb:
    container_name: rockiot_timescale
    build:
      context: ./docker/timescale
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USERNAME: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "rock_iot"
      PG_DATA: "$HOME/docker/postgres/data"
    volumes:
      - $HOME/docker/postgres/data:/var/lib/postgresql/data
    networks:
      - app-tier

  rockiot:
    depends_on:
      - timescaledb
      - rabbit1
    env_file:
      - rockiot.dev.env

  rockiotworker:
    depends_on:
      - timescaledb
      - rabbit1
      - rockiot
    env_file:
      - rockiot.dev.env

  rockiotbeat:
    depends_on:
      - timescaledb
      - rabbit1
      - rockiot
    env_file:
      - rockiot.dev.env

  rockiotlistener:
    depends_on:
      - timescaledb
      - rabbit1
      - rockiot
    env_file:
      - rockiot.dev.env

  rockiot_demo:
    build: rockiot_demo
    container_name: rockiot_demo_device1
    env_file:
      - common.env
      - rockiot.dev.env
    environment:
      - DEVICE_ID=device1
      - DEVICE_PASS=device1pass
      - DEVICE_KEY=4OrcNTFSZUrYX6NqP0P3lz
      - DEMO_IS_SSL=True
      - WAIT_HOSTS=rabbit1:8883,rockiot:8000
    depends_on:
      - rockiot
      - rockiot_ingest
    volumes:
      - $HOME/docker/certificates/:/certs/
    networks:
      - app-tier

  pgadmin:
    image: biarms/pgadmin4:4.21
    container_name: rockiot_pgadmin
    ports:
      - "5050:5050"
    depends_on:
      - timescaledb
    env_file:
      - common.env
      - rockiot.dev.env
    environment:
      - WAIT_HOSTS=timescaledb:5432,rockiot:8000
    volumes:
      - $HOME/docker/pgadmin/data:/var/lib/pgadmin
    networks:
      - app-tier

  postgresexporter:
    image: quay.io/prometheuscommunity/postgres-exporter
    container_name: postgres_exporter
    ports:
      - "9187:9187"
    depends_on:
      - timescaledb
      - rockiot
    env_file:
      - db.env
      - common.env
      - rockiot.dev.env
    environment:
      - WAIT_HOSTS=timescaledb:5432,rockiot:8000
      - DATA_SOURCE_USER=postgres
      - DATA_SOURCE_PASS=postgres
      - DATA_SOURCE_URI=timescaledb:5432/postgres?sslmode=disable
    networks:
      - app-tier