{
 "title": "ROCKIOT Delta dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Last sensor values",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"time\",$__interval),\n  device_id AS metric,\n  last(no2,\"time\") AS \"no2\",\n  last(humidity,\"time\") AS \"humidity\",\n  last(so2,\"time\") AS \"so2\",\n  last(temperature,\"time\") AS \"temperature\",\n  last(pm10,\"time\") AS \"pm10\",\n  last(pm25,\"time\") AS \"pm25\"\nFROM sensors_last_values\nWHERE\n  $__timeFilter(\"time\")\nGROUP BY 1, device_id,2\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Humidity delta",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"time\",$__interval),\n  device_id AS metric,\n  avg(humidity) - lag(avg(humidity)) OVER (PARTITION BY device_id ORDER BY $__timeGroup(\"time\",$__interval)) AS \"humidity\"\nFROM sensor_data\nWHERE\n  $__timeFilter(\"time\")\nGROUP BY 1, device_id,2\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "SO2 delta",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"time\",$__interval),\n  device_id AS metric,\n  avg(so2) - lag(avg(so2)) OVER (PARTITION BY device_id ORDER BY $__timeGroup(\"time\",$__interval)) AS \"so2\"\nFROM sensor_data\nWHERE\n  $__timeFilter(\"time\")\nGROUP BY 1, device_id,2\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "NO2 delta",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "conμgNm3" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"time\",$__interval),\n  device_id AS metric,\n  last(no2,\"time\") - lag(last(no2,\"time\")) OVER (PARTITION BY device_id ORDER BY $__timeGroup(\"time\",$__interval)) AS \"no2\"\nFROM sensor_data\nWHERE\n  $__timeFilter(\"time\")\nGROUP BY 1, device_id,2\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Temperature delta",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"time\",$__interval),\n  device_id AS metric,\n  last(temperature,\"time\") - lag(last(temperature,\"time\")) OVER (PARTITION BY device_id ORDER BY $__timeGroup(\"time\",$__interval)) AS \"temperature\"\nFROM sensor_data\nWHERE\n  $__timeFilter(\"time\")\nGROUP BY 1, device_id,2\nORDER BY 1,2"
    }
   ]
  }
 ]
}