{
 "title": "ROCKIOT MAIN Dashboard",
 "description": "ROCK IoT Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "School", "label": "Facility", "query": "select name from app_facility" }
  ]
 },
 "panels": [
  {
   "title": "Total Message Count",
   "type": "stat",
   "description": "Message Count",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(*)\nFROM sensor_data;"
    }
   ]
  },
  {
   "title": "Raw Data Count",
   "type": "stat",
   "description": "Raw Data Count for selected Period",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(*)\nFROM sensor_data\nWHERE\n  $__timeFilter(time);"
    }
   ]
  },
  {
   "title": "Average Air Quality: Temperature",
   "type": "stat",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  device_id AS metric,\n  temperature\nFROM sensor_data_rollup_15m\nWHERE\n  $__timeFilter(time)\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Average Air Quality: Humidity",
   "type": "stat",
   "description": "Average Humidity",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  device_id AS metric,\n  humidity\nFROM sensor_data_rollup_15m\nWHERE\n  $__timeFilter(time)\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Average Air Quality: NO2",
   "type": "stat",
   "description": "Average Air Quality: NO2",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  device_id AS metric,\n  no2\nFROM sensor_data_rollup_15m\nWHERE\n  $__timeFilter(time)\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Average Air Quality: SO2",
   "type": "stat",
   "description": "Average Air Quality:SO2",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  device_id AS metric,\n  so2\nFROM sensor_data_rollup_15m\nWHERE\n  $__timeFilter(time)\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Average Air Quality: PM1",
   "type": "stat",
   "description": "Average PM1",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  device_id AS metric,\n  pm1\nFROM sensor_data_rollup_15m\nWHERE\n  $__timeFilter(time)\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Average Air Quality: PM10",
   "type": "stat",
   "description": "Average PM10 ",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  device_id AS metric,\n  pm10\nFROM sensor_data_rollup_15m\nWHERE\n  $__timeFilter(time)\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Average Air Quality: PM25",
   "type": "stat",
   "description": "Average PM25",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  device_id AS metric,\n  pm25\nFROM sensor_data_rollup_15m\nWHERE\n  $__timeFilter(time)\nORDER BY 1,2"
    }
   ]
  }
 ]
}