# Generated by Django 3.2.5 on 2021-07-14 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('type', models.CharField(max_length=20, unique=True)),
                ('email', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_id', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Organizations',
                'ordering': ['created_at'],
            },
        ),
    ]
