# Generated by Django 3.2.5 on 2021-07-14 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='parent_id',
        ),
        migrations.AddField(
            model_name='organization',
            name='parent',
            field=models.ForeignKey(db_column='parent_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.organization'),
        ),
    ]
