# Generated by Django 3.2.5 on 2021-08-06 14:42
import uuid

import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_superuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=3, null=True, verbose_name='ISO Code')),
                ('mpoly', django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=4326)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Municipalities',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='device',
            name='external_id',
        ),
        migrations.RemoveField(
            model_name='device',
            name='external_key',
        ),
        migrations.AddField(
            model_name='device',
            name='lat',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='device',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='device',
            name='lon',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitude'),
        ),
        migrations.AddField(
            model_name='researcher',
            name='description',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='visitor',
            name='description',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='metadata',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='researcher',
            name='department',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='EducationFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('code', models.SlugField(default=uuid.uuid1(), max_length=64, unique=True)),
                ('type', models.CharField(choices=[('ELEMENTARY_SCHOOL', 'ELEMENTARY_SCHOOL'), ('HIGH_SCHOOL', 'HIGH_SCHOOL'), ('FACULTY', 'FACULTY'), ('UNIVERSITY', 'UNIVERSITY')], default='ELEMENTARY_SCHOOL', max_length=20)),
                ('email', models.CharField(max_length=60, validators=[django.core.validators.EmailValidator()])),
                ('description', models.CharField(max_length=250, null=True)),
                ('address', models.CharField(max_length=250)),
                ('lon', models.FloatField(blank=True, null=True, verbose_name='Longitude')),
                ('lat', models.FloatField(blank=True, null=True, verbose_name='Latitude')),
                ('location', django.contrib.gis.db.models.fields.PointField(null=True, srid=4326)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('municipality', models.ForeignKey(blank=True, db_column='municipality_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.municipality')),
            ],
            options={
                'verbose_name_plural': 'Education facilities',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='device',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='organization_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.educationfacility'),
        ),
        migrations.AlterField(
            model_name='researcher',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='organization_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.educationfacility'),
        ),
        migrations.DeleteModel(
            name='Organization',
        ),
    ]
