# Generated by Django 3.2.6 on 2021-08-06 20:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0008_alter_device_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='mode',
            field=models.CharField(choices=[('DEFAULT', 'DEFAULT'), ('CALIBRATION', 'CALIBRATION')], default='DEFAULT',
                                   max_length=20),
        ),
        migrations.AlterField(
            model_name='device',
            name='status',
            field=models.CharField(choices=[('NEW', 'NEW'), ('REGISTERED', 'REGISTERED'), ('ACTIVATED', 'ACTIVATED'),
                                            ('DEACTIVATED', 'DEACTIVATED'), ('TERMINATED', 'TERMINATED')],
                                   default='NEW', max_length=20),
        ),
    ]
