# Generated by Django 3.2.6 on 2021-08-06 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20210806_2012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='researcher',
            name='organization',
        ),
        migrations.AddField(
            model_name='device',
            name='device_pass',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='educational_facility',
            field=models.ForeignKey(blank=True, db_column='education_facility_id', null=True,
                                    on_delete=django.db.models.deletion.SET_NULL, to='app.educationfacility'),
        ),
        migrations.AddField(
            model_name='device',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='researcher',
            name='education_facility',
            field=models.ForeignKey(blank=True, db_column='education_facility_id', null=True,
                                    on_delete=django.db.models.deletion.SET_NULL, to='app.educationfacility'),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_id',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_key',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='educationfacility',
            name='email',
            field=models.EmailField(max_length=120),
        ),
    ]
