# Generated by Django 3.2.6 on 2021-08-07 00:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0010_auto_20210806_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='educationfacility',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='researcher',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
