# Generated by Django 3.2.6 on 2021-08-07 21:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0011_auto_20210807_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='status',
            field=models.CharField(
                choices=[('NEW', 'NEW'), ('REGISTERED', 'REGISTERED'), ('REGISTERING', 'REGISTERING'),
                         ('ACTIVATED', 'ACTIVATED'), ('DEACTIVATED', 'DEACTIVATED'), ('TERMINATED', 'TERMINATED')],
                default='NEW', max_length=20),
        ),
    ]
