# Generated by Django 3.2.6 on 2021-08-08 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_device_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensordata',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='sensordata',
            unique_together={('id', 'time')},
        ),
    ]