# Generated by Django 3.2.6 on 2021-08-08 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20210808_0033'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SensorData',
        ),
    ]