# Generated by Django 3.2.6 on 2021-08-09 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_delete_sensordata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='municipality',
            old_name='mpoly',
            new_name='area',
        ),
        migrations.RemoveField(
            model_name='device',
            name='active',
        ),
        migrations.AlterField(
            model_name='device',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='educational_facility',
            field=models.ForeignKey(db_column='education_facility_id', default=1, on_delete=django.db.models.deletion.PROTECT, to='app.educationfacility'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='device',
            name='metadata',
            field=models.JSONField(blank=True, default={'a': 1, 'b': 2}, null=True),
        ),
        migrations.AlterField(
            model_name='educationfacility',
            name='municipality',
            field=models.ForeignKey(db_column='municipality_id', on_delete=django.db.models.deletion.PROTECT, to='app.municipality'),
        ),
        migrations.AlterField(
            model_name='municipality',
            name='code',
            field=models.CharField(max_length=4, null=True, verbose_name='ISO Code'),
        ),
        migrations.AlterField(
            model_name='municipality',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='researcher',
            name='education_facility',
            field=models.ForeignKey(db_column='education_facility_id', on_delete=django.db.models.deletion.PROTECT, to='app.educationfacility'),
        ),
    ]