# Generated by Django 3.2.6 on 2021-08-17 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20210817_0014'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('device_id', models.CharField(max_length=30)),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=8)),
                ('humidity', models.DecimalField(decimal_places=2, max_digits=8)),
                ('co', models.DecimalField(decimal_places=2, max_digits=8)),
                ('smoke', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
            options={
                'verbose_name_plural': 'SensorData',
                'ordering': ['time'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SensorDataLastValues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('device_id', models.CharField(max_length=30)),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=8)),
                ('humidity', models.DecimalField(decimal_places=2, max_digits=8)),
                ('co', models.DecimalField(decimal_places=2, max_digits=8)),
                ('smoke', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
            options={
                'verbose_name_plural': 'SensorDataLastValues',
                'db_table': 'sensors_last_values',
                'ordering': ['time'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SensorMinutesSinceLastEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=30)),
                ('last_entry_at', models.DateTimeField(db_column='minutes_since_last_entry')),
            ],
            options={
                'verbose_name_plural': 'LastEntries',
                'db_table': 'minutes_since_last_entry',
                'ordering': ['device_id'],
                'managed': False,
            },
        )
    ]