# Generated by Django 3.2.6 on 2021-08-22 20:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20210818_1133'),
    ]

    operations = [
        migrations.CreateModel(
            name='LagDiffNO2',
            fields=[
                ('time', models.DateTimeField(primary_key=True, serialize=False)),
                ('device_id', models.CharField(max_length=30)),
                ('diff_perc', models.DecimalField(decimal_places=4, max_digits=8)),
            ],
            options={
                'verbose_name_plural': 'LagDiffNO2',
                'db_table': 'lag_diff_no2',
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LagDiffPM10',
            fields=[
                ('time', models.DateTimeField(primary_key=True, serialize=False)),
                ('device_id', models.CharField(max_length=30)),
                ('diff_perc', models.DecimalField(decimal_places=4, max_digits=8)),
            ],
            options={
                'verbose_name_plural': 'LagDiffPM10',
                'db_table': 'lag_diff_pm10',
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LagDiffPM25',
            fields=[
                ('time', models.DateTimeField(primary_key=True, serialize=False)),
                ('device_id', models.CharField(max_length=30)),
                ('diff_perc', models.DecimalField(decimal_places=4, max_digits=8)),
            ],
            options={
                'verbose_name_plural': 'LagDiffPM25',
                'db_table': 'lag_diff_pm25',
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LagDiffSO2',
            fields=[
                ('time', models.DateTimeField(primary_key=True, serialize=False)),
                ('device_id', models.CharField(max_length=30)),
                ('diff_perc', models.DecimalField(decimal_places=4, max_digits=8)),
            ],
            options={
                'verbose_name_plural': 'LagDiffSO2',
                'db_table': 'lag_diff_so2',
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SensorsSummary15Minute',
            fields=[
                ('bucket', models.DateTimeField(primary_key=True, serialize=False)),
                ('device_id', models.CharField(max_length=30)),
                ('avg_temperature', models.DecimalField(decimal_places=4, max_digits=8)),
                ('avg_humidity', models.DecimalField(decimal_places=4, max_digits=8)),
                ('avg_no2', models.DecimalField(decimal_places=4, max_digits=8)),
                ('avg_so2', models.DecimalField(decimal_places=4, max_digits=8)),
                ('avg_pm10', models.DecimalField(decimal_places=4, max_digits=8)),
                ('avg_pm25', models.DecimalField(decimal_places=4, max_digits=8)),
            ],
            options={
                'verbose_name_plural': 'SensorsSummary15Minute',
                'db_table': 'sensors_summary_15minute',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SensorsSummary4Hour',
            fields=[
                ('bucket', models.DateTimeField(primary_key=True, serialize=False)),
                ('device_id', models.CharField(max_length=30)),
                ('avg_temperature', models.DecimalField(decimal_places=4, max_digits=8)),
                ('avg_humidity', models.DecimalField(decimal_places=4, max_digits=8)),
                ('avg_no2', models.DecimalField(decimal_places=4, max_digits=8)),
                ('avg_so2', models.DecimalField(decimal_places=4, max_digits=8)),
                ('avg_pm10', models.DecimalField(decimal_places=4, max_digits=8)),
                ('avg_pm25', models.DecimalField(decimal_places=4, max_digits=8)),
            ],
            options={
                'verbose_name_plural': 'SensorsSummary4Hour',
                'db_table': 'sensors_summary_4hour',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SensorsSummaryDay',
            fields=[
                ('bucket', models.DateTimeField(primary_key=True, serialize=False)),
                ('device_id', models.CharField(max_length=30)),
                ('avg_temperature', models.DecimalField(decimal_places=4, max_digits=8)),
                ('avg_humidity', models.DecimalField(decimal_places=4, max_digits=8)),
                ('avg_no2', models.DecimalField(decimal_places=4, max_digits=8)),
                ('avg_so2', models.DecimalField(decimal_places=4, max_digits=8)),
                ('avg_pm10', models.DecimalField(decimal_places=4, max_digits=8)),
                ('avg_pm25', models.DecimalField(decimal_places=4, max_digits=8)),
            ],
            options={
                'verbose_name_plural': 'SensorsSummaryDay',
                'db_table': 'sensors_summary_day',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SensorsSummaryHour',
            fields=[
                ('bucket', models.DateTimeField(primary_key=True, serialize=False)),
                ('device_id', models.CharField(max_length=30)),
                ('avg_temperature', models.DecimalField(decimal_places=4, max_digits=8)),
                ('avg_humidity', models.DecimalField(decimal_places=4, max_digits=8)),
                ('avg_no2', models.DecimalField(decimal_places=4, max_digits=8)),
                ('avg_so2', models.DecimalField(decimal_places=4, max_digits=8)),
                ('avg_pm10', models.DecimalField(decimal_places=4, max_digits=8)),
                ('avg_pm25', models.DecimalField(decimal_places=4, max_digits=8)),
            ],
            options={
                'verbose_name_plural': 'SensorsSummaryHour',
                'db_table': 'sensors_summary_hour',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='FacilitySensorsSummaryMinute',
        ),
        migrations.DeleteModel(
            name='LagDiffCo',
        ),
        migrations.DeleteModel(
            name='LagDiffSmoke',
        ),
        migrations.DeleteModel(
            name='SensorMinutesSinceLastEntry',
        ),
        migrations.AlterModelOptions(
            name='lagdifftemperature',
            options={'managed': False, 'verbose_name_plural': 'LagDiffTemperature'},
        ),
        migrations.AlterModelOptions(
            name='sensorssummaryminute',
            options={'managed': False, 'verbose_name_plural': 'SensorsSummaryMinute'},
        ),
        migrations.AlterField(
            model_name='device',
            name='status',
            field=models.CharField(choices=[('NEW', 'NEW'), ('REGISTERED', 'REGISTERED'), ('ACTIVATED', 'ACTIVATED'), ('DEACTIVATED', 'DEACTIVATED'), ('FAULTY', 'FAULTY'), ('TERMINATED', 'TERMINATED')], default='NEW', max_length=20),
        ),
    ]