# Generated by Django 3.2.6 on 2021-08-25 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_auto_20210824_2031'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cronjob',
            options={'managed': False, 'ordering': ['jobid'], 'verbose_name': 'Data job', 'verbose_name_plural': 'Data jobs'},
        ),
        migrations.AlterModelOptions(
            name='cronjobexecution',
            options={'managed': False, 'ordering': ['jobid', 'runid'], 'verbose_name': 'Execution', 'verbose_name_plural': 'Executions'},
        ),
        migrations.AlterField(
            model_name='deviceconnection',
            name='connected_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='deviceconnection',
            name='terminated_at',
            field=models.DateTimeField(null=True),
        )
    ]