# Generated by Django 3.2.6 on 2021-08-25 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_auto_20210825_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceconnection',
            name='state',
            field=models.CharField(default='unknown', max_length=30),
        ),
    ]