# Generated by Django 3.2.7 on 2021-09-15 13:38

import app.models
from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0030_auto_20210902_1248'),
    ]

    operations = [
        migrations.CreateModel(
            name='LagDiffPM1',
            fields=[
                ('time', models.DateTimeField(primary_key=True, serialize=False)),
                ('device_id', models.CharField(max_length=30)),
                ('diff_perc', models.DecimalField(decimal_places=4, max_digits=8)),
            ],
            options={
                'verbose_name_plural': 'LagDiffPM1',
                'db_table': 'lag_diff_pm1',
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SensorsDataRollup15m',
            fields=[
                ('time', models.DateTimeField(primary_key=True, serialize=False)),
                ('device_id', models.CharField(max_length=30)),
                ('temperature', models.DecimalField(decimal_places=4, max_digits=8)),
                ('humidity', models.DecimalField(decimal_places=4, max_digits=8)),
                ('no2', models.DecimalField(decimal_places=4, max_digits=8)),
                ('so2', models.DecimalField(decimal_places=4, max_digits=8)),
                ('pm1', models.DecimalField(decimal_places=4, max_digits=8)),
                ('pm10', models.DecimalField(decimal_places=4, max_digits=8)),
                ('pm2_5', models.DecimalField(decimal_places=4, max_digits=8)),
            ],
            options={
                'verbose_name_plural': 'SensorsDataRollup15m',
                'db_table': 'sensor_data_rollup_15m',
                'ordering': ['-time'],
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricalDevice',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True, null=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(null=True, srid=4326)),
                ('device_id', models.CharField(max_length=50, null=True)),
                ('device_pass', models.CharField(max_length=128, null=True)),
                ('status', models.CharField(choices=[('NEW', 'NEW'), ('REGISTERED', 'REGISTERED'), ('ACTIVATED', 'ACTIVATED'), ('DEACTIVATED', 'DEACTIVATED'), ('FAULTY', 'FAULTY'), ('TERMINATED', 'TERMINATED')], default='NEW', max_length=20)),
                ('mode', models.CharField(choices=[('DEFAULT', 'DEFAULT'), ('CALIBRATION', 'CALIBRATION'), ('CALIBRATION', 'PRODUCTION')], default='DEFAULT', max_length=20)),
                ('metadata', models.JSONField(default=app.models.default_device_metadata)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical device',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.DeleteModel(
            name='SensorsDataRollup5m',
        ),
        migrations.AlterModelOptions(
            name='sensorsdatarollup1h',
            options={'managed': False, 'ordering': ['-time'], 'verbose_name_plural': 'SensorsDataRollup1h'},
        ),
        migrations.AlterModelOptions(
            name='sensorsdatarollup24h',
            options={'managed': False, 'ordering': ['-time'], 'verbose_name_plural': 'SensorsDataRollup24h'},
        ),
        migrations.AlterModelOptions(
            name='sensorsdatarollup4h',
            options={'managed': False, 'ordering': ['-time'], 'verbose_name_plural': 'SensorsDataRollup4h'},
        ),
        migrations.AlterField(
            model_name='device',
            name='mode',
            field=models.CharField(choices=[('DEFAULT', 'DEFAULT'), ('CALIBRATION', 'CALIBRATION'), ('PRODUCTION', 'PRODUCTION')], default='DEFAULT', max_length=20),
        ),
        migrations.AddField(
            model_name='historicaldevice',
            name='facility',
            field=models.ForeignKey(blank=True, db_column='facility_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.facility'),
        ),
        migrations.AddField(
            model_name='historicaldevice',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]