# Generated by Django 3.2.7 on 2021-09-20 19:09

import app.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_auto_20210915_1338'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorDataRaw',
            fields=[
                ('time', models.DateTimeField(primary_key=True, serialize=False)),
                ('device_id', models.CharField(max_length=30)),
                ('client_id', models.CharField(max_length=30)),
                ('data', models.JSONField(default=app.models.default_data_row)),
            ],
            options={
                'db_table': 'sensor_data_raw',
                'ordering': ['-time'],
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='historicaldevice',
            name='history_change_reason',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='historicaldevice',
            name='profile',
            field=models.CharField(choices=[('DEFAULT', 'DEFAULT'), ('CALIBRATION', 'CALIBRATION'), ('PRODUCTION', 'PRODUCTION')], default='DEFAULT', max_length=15),
        ),
        migrations.CreateModel(
            name='DeviceCalibrationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.CharField(default='0 1 0', max_length=20)),
                ('humidity', models.CharField(default='0 1 0', max_length=20)),
                ('no2', models.CharField(default='0 1 0', max_length=20)),
                ('so2', models.CharField(default='0 1 0', max_length=20)),
                ('pm1', models.CharField(default='0 1 0', max_length=20)),
                ('pm10', models.CharField(default='0 1 0', max_length=20)),
                ('pm2_5', models.CharField(default='0 1 0', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(db_column='device_id', on_delete=django.db.models.deletion.CASCADE, related_name='calibration_models', to='app.device')),
            ],
        ),
    ]
