# Generated by Django 3.2.7 on 2021-09-29 21:56

import app.models
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_periodict_tasks'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devicelogentry',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'Devices log'},
        ),
        migrations.AlterField(
            model_name='device',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(default=app.models.belgrade_location_point, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='devicecalibrationmodel',
            name='humidity',
            field=app.models.CommaSeparatedStringsField(default='0, 1, 0', max_length=20),
        ),
        migrations.AlterField(
            model_name='devicecalibrationmodel',
            name='no2',
            field=app.models.CommaSeparatedStringsField(default='0, 1, 0', max_length=20),
        ),
        migrations.AlterField(
            model_name='devicecalibrationmodel',
            name='pm1',
            field=app.models.CommaSeparatedStringsField(default='0, 1, 0', max_length=20),
        ),
        migrations.AlterField(
            model_name='devicecalibrationmodel',
            name='pm10',
            field=app.models.CommaSeparatedStringsField(default='0, 1, 0', max_length=20),
        ),
        migrations.AlterField(
            model_name='devicecalibrationmodel',
            name='pm2_5',
            field=app.models.CommaSeparatedStringsField(default='0, 1, 0', max_length=20),
        ),
        migrations.AlterField(
            model_name='devicecalibrationmodel',
            name='so2',
            field=app.models.CommaSeparatedStringsField(default='0, 1, 0', max_length=20),
        ),
        migrations.AlterField(
            model_name='devicecalibrationmodel',
            name='temperature',
            field=app.models.CommaSeparatedStringsField(default='0, 1, 0', max_length=20),
        ),
        migrations.AlterField(
            model_name='devicelogentry',
            name='history_change_reason',
            field=models.TextField(blank=True, default='Values changed', null=True),
        ),
        migrations.AlterField(
            model_name='devicelogentry',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(default=app.models.belgrade_location_point, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='devicelogentry',
            name='mode',
            field=models.CharField(choices=[('DEFAULT', 'DEFAULT'), ('CALIBRATION', 'CALIBRATION'), ('PRODUCTION', 'PRODUCTION')], default='DEFAULT', max_length=20),
        ),
        migrations.AlterField(
            model_name='facility',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(default=app.models.belgrade_location_point, null=True, srid=4326),
        ),
    ]
