# Generated by Django 3.2.8 on 2021-10-07 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_auto_20210929_2156'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LagDiffHumidity',
        ),
        migrations.DeleteModel(
            name='LagDiffNO2',
        ),
        migrations.DeleteModel(
            name='LagDiffPM1',
        ),
        migrations.DeleteModel(
            name='LagDiffPM10',
        ),
        migrations.DeleteModel(
            name='LagDiffPM2_5',
        ),
        migrations.DeleteModel(
            name='LagDiffSO2',
        ),
        migrations.DeleteModel(
            name='LagDiffTemperature',
        ),
    ]