# Generated by Django 3.2.8 on 2021-10-10 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_auto_20211007_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='zero_config_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='devicelogentry',
            name='zero_config_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]