# Generated by Django 3.2.8 on 2021-10-12 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_auto_20211010_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='erase_wifi_credentials_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='devicelogentry',
            name='erase_wifi_credentials_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]