# Generated by Django 3.2.8 on 2021-10-15 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_auto_20211012_1634'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='erase_wifi_credentials_at',
            new_name='last_event_sent_at',
        ),
        migrations.RemoveField(
            model_name='device',
            name='zero_config_at',
        ),
        migrations.RenameField(
            model_name='devicelogentry',
            old_name='erase_wifi_credentials_at',
            new_name='last_event_sent_at',
        ),
        migrations.RemoveField(
            model_name='devicelogentry',
            name='zero_config_at',
        ),
    ]