# Generated by Django 3.2.8 on 2021-10-30 20:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_auto_20211027_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertscheme',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alertscheme',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]