# Generated by Django 3.2.9 on 2021-12-10 21:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_preferences', '0007_alter_globalpreferencemodel_id'),
        ('app', '0043_auto_20211030_2209'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor15mAverageFacility',
            fields=[
                ('code', models.CharField(max_length=30)),
                ('time', models.DateTimeField(primary_key=True, serialize=False)),
                ('temperature', models.DecimalField(decimal_places=4, max_digits=16)),
                ('humidity', models.DecimalField(decimal_places=4, max_digits=16)),
                ('no2', models.DecimalField(decimal_places=4, max_digits=16)),
                ('so2', models.DecimalField(decimal_places=4, max_digits=16)),
                ('pm1', models.DecimalField(decimal_places=4, max_digits=16)),
                ('pm10', models.DecimalField(decimal_places=4, max_digits=16)),
                ('pm2_5', models.DecimalField(decimal_places=4, max_digits=16)),
            ],
            options={
                'db_table': 'sensor_data_15m_average_facility',
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sensor15mAverageMunicipality',
            fields=[
                ('code', models.CharField(max_length=30)),
                ('time', models.DateTimeField(primary_key=True, serialize=False)),
                ('temperature', models.DecimalField(decimal_places=4, max_digits=16)),
                ('humidity', models.DecimalField(decimal_places=4, max_digits=16)),
                ('no2', models.DecimalField(decimal_places=4, max_digits=16)),
                ('so2', models.DecimalField(decimal_places=4, max_digits=16)),
                ('pm1', models.DecimalField(decimal_places=4, max_digits=16)),
                ('pm10', models.DecimalField(decimal_places=4, max_digits=16)),
                ('pm2_5', models.DecimalField(decimal_places=4, max_digits=16)),
            ],
            options={
                'db_table': 'sensor_data_15m_average_municipality',
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sensor1hAverageFacility',
            fields=[
                ('code', models.CharField(max_length=30)),
                ('time', models.DateTimeField(primary_key=True, serialize=False)),
                ('temperature', models.DecimalField(decimal_places=4, max_digits=16)),
                ('humidity', models.DecimalField(decimal_places=4, max_digits=16)),
                ('no2', models.DecimalField(decimal_places=4, max_digits=16)),
                ('so2', models.DecimalField(decimal_places=4, max_digits=16)),
                ('pm1', models.DecimalField(decimal_places=4, max_digits=16)),
                ('pm10', models.DecimalField(decimal_places=4, max_digits=16)),
                ('pm2_5', models.DecimalField(decimal_places=4, max_digits=16)),
            ],
            options={
                'db_table': 'sensor_data_hour_average_facility',
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sensor1hAverageMunicipality',
            fields=[
                ('code', models.CharField(max_length=30)),
                ('time', models.DateTimeField(primary_key=True, serialize=False)),
                ('temperature', models.DecimalField(decimal_places=4, max_digits=16)),
                ('humidity', models.DecimalField(decimal_places=4, max_digits=16)),
                ('no2', models.DecimalField(decimal_places=4, max_digits=16)),
                ('so2', models.DecimalField(decimal_places=4, max_digits=16)),
                ('pm1', models.DecimalField(decimal_places=4, max_digits=16)),
                ('pm10', models.DecimalField(decimal_places=4, max_digits=16)),
                ('pm2_5', models.DecimalField(decimal_places=4, max_digits=16)),
            ],
            options={
                'db_table': 'sensor_data_hour_average_municipality',
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sensor24hAverageFacility',
            fields=[
                ('code', models.CharField(max_length=30)),
                ('time', models.DateTimeField(primary_key=True, serialize=False)),
                ('temperature', models.DecimalField(decimal_places=4, max_digits=16)),
                ('humidity', models.DecimalField(decimal_places=4, max_digits=16)),
                ('no2', models.DecimalField(decimal_places=4, max_digits=16)),
                ('so2', models.DecimalField(decimal_places=4, max_digits=16)),
                ('pm1', models.DecimalField(decimal_places=4, max_digits=16)),
                ('pm10', models.DecimalField(decimal_places=4, max_digits=16)),
                ('pm2_5', models.DecimalField(decimal_places=4, max_digits=16)),
            ],
            options={
                'db_table': 'sensor_data_day_average_facility',
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sensor24hAverageMunicipality',
            fields=[
                ('code', models.CharField(max_length=30)),
                ('time', models.DateTimeField(primary_key=True, serialize=False)),
                ('temperature', models.DecimalField(decimal_places=4, max_digits=16)),
                ('humidity', models.DecimalField(decimal_places=4, max_digits=16)),
                ('no2', models.DecimalField(decimal_places=4, max_digits=16)),
                ('so2', models.DecimalField(decimal_places=4, max_digits=16)),
                ('pm1', models.DecimalField(decimal_places=4, max_digits=16)),
                ('pm10', models.DecimalField(decimal_places=4, max_digits=16)),
                ('pm2_5', models.DecimalField(decimal_places=4, max_digits=16)),
            ],
            options={
                'db_table': 'sensor_data_day_average_municipality',
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sensor4hAverageFacility',
            fields=[
                ('code', models.CharField(max_length=30)),
                ('time', models.DateTimeField(primary_key=True, serialize=False)),
                ('temperature', models.DecimalField(decimal_places=4, max_digits=16)),
                ('humidity', models.DecimalField(decimal_places=4, max_digits=16)),
                ('no2', models.DecimalField(decimal_places=4, max_digits=16)),
                ('so2', models.DecimalField(decimal_places=4, max_digits=16)),
                ('pm1', models.DecimalField(decimal_places=4, max_digits=16)),
                ('pm10', models.DecimalField(decimal_places=4, max_digits=16)),
                ('pm2_5', models.DecimalField(decimal_places=4, max_digits=16)),
            ],
            options={
                'db_table': 'sensor_data_4hour_average_facility',
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sensor4hAverageMunicipality',
            fields=[
                ('code', models.CharField(max_length=30)),
                ('time', models.DateTimeField(primary_key=True, serialize=False)),
                ('temperature', models.DecimalField(decimal_places=4, max_digits=16)),
                ('humidity', models.DecimalField(decimal_places=4, max_digits=16)),
                ('no2', models.DecimalField(decimal_places=4, max_digits=16)),
                ('so2', models.DecimalField(decimal_places=4, max_digits=16)),
                ('pm1', models.DecimalField(decimal_places=4, max_digits=16)),
                ('pm10', models.DecimalField(decimal_places=4, max_digits=16)),
                ('pm2_5', models.DecimalField(decimal_places=4, max_digits=16)),
            ],
            options={
                'db_table': 'sensor_data_4hour_average_municipality',
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AqCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pollutant', models.CharField(max_length=16)),
                ('timeframe', models.CharField(choices=[('1h', '1h'), ('4h', '4h'), ('24h', '24h'), ('15m', '15m')], default='1h', max_length=10)),
                ('lower_limit', models.IntegerField()),
                ('upper_limit', models.IntegerField()),
            ],
            options={
                'db_table': 'aq_category',
            },
        ),
        migrations.CreateModel(
            name='AqClassification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'aq_classification',
            },
        ),
        migrations.DeleteModel(
            name='SensorDayAverageFacility',
        ),
        migrations.DeleteModel(
            name='SensorDayAverageMunicipality',
        ),
        migrations.DeleteModel(
            name='SensorHourAverageFacility',
        ),
        migrations.DeleteModel(
            name='SensorHourAverageMunicipality',
        ),
        migrations.CreateModel(
            name='RockiotGlobalPreferenceModel',
            fields=[
            ],
            options={
                'verbose_name': 'Global preference',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('dynamic_preferences.globalpreferencemodel',),
        ),
        migrations.AlterField(
            model_name='facility',
            name='code',
            field=models.SlugField(blank=True, default=uuid.UUID('bd517788-5a03-11ec-9fd3-0242ac120005'), max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='municipality',
            name='code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='aqcategory',
            name='classification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='app.aqclassification'),
        ),
    ]
