# Generated by Django 3.2.9 on 2021-12-12 22:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_preferences', '0007_alter_globalpreferencemodel_id'),
        ('app', '0044_auto_20211210_2154'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor15mAverageFacility',
            fields=[
                ('code', models.CharField(max_length=30)),
                ('time', models.DateTimeField(primary_key=True, serialize=False)),
                ('temperature', models.DecimalField(decimal_places=4, max_digits=16)),
                ('humidity', models.DecimalField(decimal_places=4, max_digits=16)),
                ('no2', models.DecimalField(decimal_places=4, max_digits=16)),
                ('so2', models.DecimalField(decimal_places=4, max_digits=16)),
                ('pm1', models.DecimalField(decimal_places=4, max_digits=16)),
                ('pm10', models.DecimalField(decimal_places=4, max_digits=16)),
                ('pm2_5', models.DecimalField(decimal_places=4, max_digits=16)),
            ],
            options={
                'db_table': 'sensor_data_15m_average_facility',
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sensor15mAverageMunicipality',
            fields=[
                ('code', models.CharField(max_length=30)),
                ('time', models.DateTimeField(primary_key=True, serialize=False)),
                ('temperature', models.DecimalField(decimal_places=4, max_digits=16)),
                ('humidity', models.DecimalField(decimal_places=4, max_digits=16)),
                ('no2', models.DecimalField(decimal_places=4, max_digits=16)),
                ('so2', models.DecimalField(decimal_places=4, max_digits=16)),
                ('pm1', models.DecimalField(decimal_places=4, max_digits=16)),
                ('pm10', models.DecimalField(decimal_places=4, max_digits=16)),
                ('pm2_5', models.DecimalField(decimal_places=4, max_digits=16)),
            ],
            options={
                'db_table': 'sensor_data_15m_average_municipality',
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sensor1hAverageFacility',
            fields=[
                ('code', models.CharField(max_length=30)),
                ('time', models.DateTimeField(primary_key=True, serialize=False)),
                ('temperature', models.DecimalField(decimal_places=4, max_digits=16)),
                ('humidity', models.DecimalField(decimal_places=4, max_digits=16)),
                ('no2', models.DecimalField(decimal_places=4, max_digits=16)),
                ('so2', models.DecimalField(decimal_places=4, max_digits=16)),
                ('pm1', models.DecimalField(decimal_places=4, max_digits=16)),
                ('pm10', models.DecimalField(decimal_places=4, max_digits=16)),
                ('pm2_5', models.DecimalField(decimal_places=4, max_digits=16)),
            ],
            options={
                'db_table': 'sensor_data_hour_average_facility',
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sensor1hAverageMunicipality',
            fields=[
                ('code', models.CharField(max_length=30)),
                ('time', models.DateTimeField(primary_key=True, serialize=False)),
                ('temperature', models.DecimalField(decimal_places=4, max_digits=16)),
                ('humidity', models.DecimalField(decimal_places=4, max_digits=16)),
                ('no2', models.DecimalField(decimal_places=4, max_digits=16)),
                ('so2', models.DecimalField(decimal_places=4, max_digits=16)),
                ('pm1', models.DecimalField(decimal_places=4, max_digits=16)),
                ('pm10', models.DecimalField(decimal_places=4, max_digits=16)),
                ('pm2_5', models.DecimalField(decimal_places=4, max_digits=16)),
            ],
            options={
                'db_table': 'sensor_data_hour_average_municipality',
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sensor24hAverageFacility',
            fields=[
                ('code', models.CharField(max_length=30)),
                ('time', models.DateTimeField(primary_key=True, serialize=False)),
                ('temperature', models.DecimalField(decimal_places=4, max_digits=16)),
                ('humidity', models.DecimalField(decimal_places=4, max_digits=16)),
                ('no2', models.DecimalField(decimal_places=4, max_digits=16)),
                ('so2', models.DecimalField(decimal_places=4, max_digits=16)),
                ('pm1', models.DecimalField(decimal_places=4, max_digits=16)),
                ('pm10', models.DecimalField(decimal_places=4, max_digits=16)),
                ('pm2_5', models.DecimalField(decimal_places=4, max_digits=16)),
            ],
            options={
                'db_table': 'sensor_data_day_average_facility',
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sensor24hAverageMunicipality',
            fields=[
                ('code', models.CharField(max_length=30)),
                ('time', models.DateTimeField(primary_key=True, serialize=False)),
                ('temperature', models.DecimalField(decimal_places=4, max_digits=16)),
                ('humidity', models.DecimalField(decimal_places=4, max_digits=16)),
                ('no2', models.DecimalField(decimal_places=4, max_digits=16)),
                ('so2', models.DecimalField(decimal_places=4, max_digits=16)),
                ('pm1', models.DecimalField(decimal_places=4, max_digits=16)),
                ('pm10', models.DecimalField(decimal_places=4, max_digits=16)),
                ('pm2_5', models.DecimalField(decimal_places=4, max_digits=16)),
            ],
            options={
                'db_table': 'sensor_data_day_average_municipality',
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sensor4hAverageFacility',
            fields=[
                ('code', models.CharField(max_length=30)),
                ('time', models.DateTimeField(primary_key=True, serialize=False)),
                ('temperature', models.DecimalField(decimal_places=4, max_digits=16)),
                ('humidity', models.DecimalField(decimal_places=4, max_digits=16)),
                ('no2', models.DecimalField(decimal_places=4, max_digits=16)),
                ('so2', models.DecimalField(decimal_places=4, max_digits=16)),
                ('pm1', models.DecimalField(decimal_places=4, max_digits=16)),
                ('pm10', models.DecimalField(decimal_places=4, max_digits=16)),
                ('pm2_5', models.DecimalField(decimal_places=4, max_digits=16)),
            ],
            options={
                'db_table': 'sensor_data_4hour_average_facility',
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sensor4hAverageMunicipality',
            fields=[
                ('code', models.CharField(max_length=30)),
                ('time', models.DateTimeField(primary_key=True, serialize=False)),
                ('temperature', models.DecimalField(decimal_places=4, max_digits=16)),
                ('humidity', models.DecimalField(decimal_places=4, max_digits=16)),
                ('no2', models.DecimalField(decimal_places=4, max_digits=16)),
                ('so2', models.DecimalField(decimal_places=4, max_digits=16)),
                ('pm1', models.DecimalField(decimal_places=4, max_digits=16)),
                ('pm10', models.DecimalField(decimal_places=4, max_digits=16)),
                ('pm2_5', models.DecimalField(decimal_places=4, max_digits=16)),
            ],
            options={
                'db_table': 'sensor_data_4hour_average_municipality',
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='SensorDayAverageFacility',
        ),
        migrations.DeleteModel(
            name='SensorDayAverageMunicipality',
        ),
        migrations.DeleteModel(
            name='SensorHourAverageFacility',
        ),
        migrations.DeleteModel(
            name='SensorHourAverageMunicipality',
        ),
        migrations.CreateModel(
            name='RockiotGlobalPreferenceModel',
            fields=[
            ],
            options={
                'verbose_name': 'Global preference',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('dynamic_preferences.globalpreferencemodel',),
        ),
        migrations.AlterField(
            model_name='aqcategory',
            name='pollutant',
            field=models.CharField(choices=[('TEMPERATURE', 'TEMPERATURE'), ('HUMIDITY', 'HUMIDITY'), ('PM1', 'PM1'), ('PM2_5', 'PM2_5'), ('PM10', 'PM10'), ('NO2', 'NO2'), ('SO2', 'SO2')], default='PM1', max_length=16),
        ),
        migrations.AlterField(
            model_name='aqclassification',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='facility',
            name='code',
            field=models.SlugField(blank=True, default=uuid.UUID('4c75922e-5b9d-11ec-ab41-0242ac120005'), max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='municipality',
            name='code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
