global:
  slack_api_url: https://hooks.slack.com/services/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

route:
  receiver: 'discord_webhook'
  group_wait: 1m
  group_interval: 5m
  repeat_interval: 30m
  group_by: [alarmname, device]
  routes:
    - receiver: 'discord_webhook'
      repeat_interval: 1h
    - receiver: 'slack-notifications'
      repeat_interval: 1h

receivers:
- name: 'discord_webhook'
  webhook_configs:
  - url: 'http://localhost:9094'
    max_alerts: 3
- name: 'slack-notifications'
  slack_configs:
  - channel: '#qza'
    send_resolved: true
    icon_url: https://avatars3.githubusercontent.com/u/3380462
    title: |-
     [{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ .CommonLabels.alertname }} for {{ .CommonLabels.job }}
     {{- if gt (len .CommonLabels) (len .GroupLabels) -}}
       {{" "}}(
       {{- with .CommonLabels.Remove .GroupLabels.Names }}
         {{- range $index, $label := .SortedPairs -}}
           {{ if $index }}, {{ end }}
           {{- $label.Name }}="{{ $label.Value -}}"
         {{- end }}
       {{- end -}}
       )
     {{- end }}
    text: >-
     {{ range .Alerts -}}
     *Alert:* {{ .Annotations.summary }}{{ if .Labels.severity }} - `{{ .Labels.severity }}`{{ end }}

     *Description:* {{ .Annotations.description }}

     *Details:*
       {{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`
       {{ end }}
     {{ end }}