# https://prometheus.io/docs/prometheus/latest/configuration/configuration/
global:
  # This is higher than RabbitMQ's collect_statistics_interval,
  # but still close enough to capture metrics that were refreshed within this interval
  # This value determines the range that we use with rate():
  # https://www.robustperception.io/what-range-should-i-use-with-rate

  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 30s

alerting:
  alertmanagers:
  - static_configs:
    - targets:
       - 'alertmanager:9093'

rule_files:
   - "system_rules.yml"
   - "rabbitmq_rules.yml"
   - "postgres_rules.yml"

scrape_configs:

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'nodeexporter'
    static_configs:
      - targets: [ 'nodeexporter:9100' ]

  - job_name: 'rabbitmq-exporter'
    static_configs:
      - targets: [ 'rabbit1:15692' ]

  - job_name: 'postgres-exporter'
    static_configs:
      - targets: [ 'postgresexporter:9187' ]