groups:
  - name: rabbit-mq
    rules:
      - alert: RabbitmqTooManyConnections
        expr: rabbitmq_connections > 1000
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: Rabbitmq too many connections (instance {{ $labels.instance }})
          description: "The total connections of a node is too high {{ $value }}"

      - alert: RabbitmqMemoryHigh
        expr: rabbitmq_process_resident_memory_bytes / rabbitmq_resident_memory_limit_bytes * 100 > 90
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: Rabbitmq memory high (instance {{ $labels.instance }})
          description: "A node use more than 90% of allocated RAM {{ $value }}"

      - alert: RabbitmqFileDescriptorsUsage
        expr: rabbitmq_process_open_fds / rabbitmq_process_max_fds * 100 > 90
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: Rabbitmq file descriptors usage (instance {{ $labels.instance }})
          description: "A node use more than 90% of file descriptors {{ $value }}"

      - alert: RabbitmqTooManyUnackMessages
        expr: sum(rabbitmq_queue_messages_unacked) by (queue) > 100
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: Rabbitmq too many unack messages (instance {{ $labels.instance }})
          description: "Too many unacknowledged messages {{ $value }}"

      - alert: RabbitmqNoQueueConsumer
        expr: rabbitmq_queue_consumers{queue=~".*amqp.*"} < 1
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: Rabbitmq no queue consumer (instance {{ $labels.instance }})
          description: "A queue has less than 1 consumer {{ $value }}"
