groups:
  - name: rockiot
    rules:
      - alert: DeviceMetadataNotUpdated
        expr: time() - rockiot_metadata_saved > 1200 and rockiot_connected == 1
        for: 0m
        labels:
          severity: warning
        annotations:
          summary: Device metadata not updated (device {{ $labels.device }})
          description: "Device {{ $labels.device }} metadata not updated. Last update before: {{ $value | humanizeDuration }}"

      - alert: DeviceNotIngestingData
        expr: time() - rockiot_last_ingest > 180 and rockiot_connected == 1
        for: 0m
        labels:
          severity: warning
        annotations:
          summary: Device is not ingesting data (device {{ $labels.device }})
          description: "Device {{ $labels.device }} sensor data not ingested recently. Last update before: {{ $value | humanizeDuration }}"

      - alert: DeviceTooManyTerminatedConnections
        expr: increase(rockiot_connection_terminated[1h]) > 10
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: Device has too many terminated connections in last hour (device {{ $labels.device }})
          description: "Device {{ $labels.device }} is terminating connections to often. Terminated {{ $value }} connections in last hour"

      - alert: DeviceConnectionLost
        expr: max_over_time(rockiot_connected[45m]) < 1
        for: 15m
        labels:
          severity: warning
          oneshot: true
        annotations:
          summary: Device {{ $labels.device }} is offline
          description: "Device {{ $labels.device }} has been offline during the last hour"
