apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    url: timescaledb:5432
    database: rock_iot
    user: postgres
    secureJsonData:
      password: 'postgres'
    jsonData:
      sslmode: 'disable'
      maxOpenConns: 0
      maxIdleConns: 4
      connMaxLifetime: 14400
      postgresVersion: 1200
      timescaledb: true
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://prometheus:9090
    isDefault: false
    version: 1
    editable: false
  - name: Loki
    type: loki
    orgId: 1
    url: loki:3100
    access: proxy
    isDefault: false
    version: 1
    editable: false
    jsonData:
      maxLines: 1000